<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <Configurations>Release;LamaDebug</Configurations>
    <Version>0</Version>
    <Authors>The team members are listed in README.md file on project web page.</Authors>
    <Company>Atesh Entertainment Inc.</Company>
    <Description>Atesh.Metalama library is a collection of custom made Metalama Aspects (a.k.a Attributes).</Description>
    <PackageProjectUrl>https://bitbucket.org/XtroTheArctic/atesh.metalama</PackageProjectUrl>
    <RepositoryUrl>git@bitbucket.org:XtroTheArctic/atesh.metalama</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>Atesh, Metalama, PostSharp, Aspect, Attribute</PackageTags>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.0.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin</OutputPath>
    <NoWarn />
    <WarningsAsErrors />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LamaDebug|AnyCPU'">
    <NoWarn />
    <WarningsAsErrors />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Atesh.Metalama.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Metalama.Framework" Version="0.5.41-preview" />
  </ItemGroup>

</Project>
