<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Release;LamaDebug</Configurations>
    <Version>0</Version>
    <Authors>The team members are listed in README.md file on project web page.</Authors>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <Company>Atesh Entertainment Inc.</Company>
    <Description>Atesh.Metalama library is a collection of custom made Metalama Aspects (a.k.a Attributes).</Description>
    <PackageProjectUrl>https://bitbucket.org/XtroTheArctic/atesh.metalama</PackageProjectUrl>
    <RepositoryUrl>git@bitbucket.org:XtroTheArctic/atesh.metalama</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>Atesh, Metalama, PostSharp, Aspect, Attribute</PackageTags>
    <MetalamaLicense>111976-ZQMC8QQQXEAEQRQCB88YNBFRY2EWBQGVS8KTX7YDS29ZXNSRF4UWBZUAAZ9CNJAFVD6CXMSRR4UMNTDAEJ8QB6WGK6W35S65EU5WTDMSWE7EL2WBLF2Q4UUYTPPFZ3NN6H97CDPJHAD2J83UYMZQQDE9YUWZTCWQL5AR27W3VJRL5</MetalamaLicense>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin</OutputPath>
    <NoWarn />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='LamaDebug|AnyCPU'">
    <NoWarn />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Atesh.Metalama.csproj.DotSettings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Metalama.Framework" Version="2024.2.18" />
    <PackageReference Include="Metalama.Patterns.Contracts" Version="2024.2.18" />
  </ItemGroup>

</Project>
